FROM elixir:1.4

RUN apt-get update \
    && apt-get install -y postgresql-client \
    && apt-get install -y inotify-tools \
    && apt-get clean



ENV MIX_ENV=dev

# Install Phoenix 1.3
RUN mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phx_new.ez

# Install NodeJS
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && apt-get install -y nodejs

RUN mkdir /app
WORKDIR /app

RUN mix do local.hex --force, local.rebar --force

# Cache elixir deps
COPY config/ /app/config/
COPY mix.exs mix.lock /app/
RUN  mix deps.get

# Install JS dependencies
WORKDIR /app/assets
COPY assets/ ./
RUN npm install

WORKDIR /app
ADD . .
EXPOSE 5000
CMD mix phx.server
