# TODO: Make compose file work for non-dev environments too
#
web:
  build: .
  command: mix phx.server
  ports:
    # On some LM macs nxd (NX daemon) may be running on 4000
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - postgres

postgres:
  image: postgres:9.6
  ports:
    - "5432"
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  volumes:
    - ./postgres-data:/var/lib/postgresql/data
