FROM elixir:1.4.5 as mix-getter

ENV HOME=/app

RUN mix do local.hex --force, local.rebar --force

# Cache elixir deps
COPY config/ $HOME/config/
COPY mix.exs mix.lock $HOME/

WORKDIR $HOME/apps/gml
RUN mix deps.get

########################################################################
FROM node:6 as asset-builder

ENV HOME=/app
WORKDIR $HOME

COPY --from=mix-getter $HOME/deps $HOME/deps

WORKDIR $HOME/apps/gml/assets
COPY apps/gml/assets/ ./
RUN yarn install
RUN ./node_modules/.bin/brunch build -e test

########################################################################
FROM bitwalker/alpine-elixir:1.4.5 as tester

ENV HOME=/app

ARG ERLANG_COOKIE
ENV ERLANG_COOKIE $ERLANG_COOKIE

# dependencies for comeonin
RUN apk add --no-cache build-base cmake

# Install Hex + Rebar
RUN mix do local.hex --force, local.rebar --force

# Cache elixir deps
COPY config/ $HOME/config/
COPY mix.exs mix.lock $HOME/

ENV MIX_ENV=test
RUN mix do deps.get --only $MIX_ENV, deps.compile

COPY . $HOME/

ENV LANG=en_US.UTF-8 \
    HOME=/app/ \
    TERM=xterm

RUN apk add --no-cache ncurses-libs openssl

EXPOSE 5000
WORKDIR $HOME
CMD bash -c '/app/scripts/unit-tests.sh'
