#
# This is a _good enough_ Dockerfile
#
# What we want ultimately is to use Distillery and make the final image as small as possible.
# This one leaves behind the source and node.  Also, it builds from exlixir:latest which uses
# Debian Jessie (not slim) and drags in a lot of build tools.
#

FROM elixir:latest

# netcat and dnsutils are for Codefresh to wait on DB from inside container
RUN apt-get update \
    && apt-get install -y postgresql-client \
    && apt-get install -y netcat \
    && apt-get install -y dnsutils \
    && apt-get install -y inotify-tools \
    && apt-get clean

# Install Phoenix 1.3
RUN mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phx_new.ez

# Install NodeJS
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && apt-get install -y nodejs

RUN mkdir /app
WORKDIR /app
ADD . .

# Install app dependencies
RUN mix local.hex --force \
    && mix local.rebar --force \
    && mix deps.get

# Install JS dependencies
WORKDIR /app/assets
RUN npm install --prefix /app/assets

EXPOSE 5000

WORKDIR /app
CMD mix phx.server
