branch-defaults:
  master:
    environment: GML-Production
environment-defaults:
  GML-Production:
    branch: null
    repository: null
global:
  application_name: GMLPOC
  default_ec2_keyname: placey-ec2-key
  default_platform: Docker 17.03.1-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
